ADDRESSES = [
    {
        "address_id": "MXCDMX-001",
        "city": "Ciudad de Mexico",
        "zone": "Roma Norte",
        "zone_type": "alta demanda",
        "address": "Av. Alvaro Obregon 120, Roma Norte, CDMX",
        "rationale": "Zona densa con alta oferta restaurantera y usuarios premium.",
    },
    {
        "address_id": "MXCDMX-002",
        "city": "Ciudad de Mexico",
        "zone": "Condesa",
        "zone_type": "alta demanda",
        "address": "Av. Tamaulipas 150, Condesa, CDMX",
        "rationale": "Zona competitiva con alta adopcion de delivery.",
    },
    {
        "address_id": "MXCDMX-003",
        "city": "Ciudad de Mexico",
        "zone": "Polanco",
        "zone_type": "premium",
        "address": "Av. Presidente Masaryk 320, Polanco, CDMX",
        "rationale": "Zona premium sensible a surtido y tiempos.",
    },
    {
        "address_id": "MXCDMX-004",
        "city": "Ciudad de Mexico",
        "zone": "Santa Fe",
        "zone_type": "corporativa",
        "address": "Av. Vasco de Quiroga 3800, Santa Fe, CDMX",
        "rationale": "Zona corporativa con picos de almuerzo.",
    },
    {
        "address_id": "MXCDMX-005",
        "city": "Ciudad de Mexico",
        "zone": "Coyoacan",
        "zone_type": "residencial",
        "address": "Miguel Angel de Quevedo 687, Coyoacan, CDMX",
        "rationale": "Zona residencial con comportamiento distinto a zonas premium.",
    },
    {
        "address_id": "MXCDMX-006",
        "city": "Ciudad de Mexico",
        "zone": "Narvarte",
        "zone_type": "residencial",
        "address": "Av. Universidad 740, Narvarte, CDMX",
        "rationale": "Zona media con buena cobertura de restaurantes.",
    },
    {
        "address_id": "MXCDMX-007",
        "city": "Ciudad de Mexico",
        "zone": "Iztapalapa",
        "zone_type": "periferica",
        "address": "Av. Ermita Iztapalapa 1800, Iztapalapa, CDMX",
        "rationale": "Zona periferica para medir competitividad de fees.",
    },
    {
        "address_id": "MXCDMX-008",
        "city": "Ciudad de Mexico",
        "zone": "Lindavista",
        "zone_type": "residencial",
        "address": "Av. Montevideo 303, Lindavista, CDMX",
        "rationale": "Zona norte residencial con oferta mixta.",
    },
    {
        "address_id": "MXCDMX-009",
        "city": "Ciudad de Mexico",
        "zone": "Tlalpan",
        "zone_type": "periferica",
        "address": "Calz. de Tlalpan 4500, Tlalpan, CDMX",
        "rationale": "Zona sur para evaluar cobertura operacional.",
    },
    {
        "address_id": "MXCDMX-010",
        "city": "Ciudad de Mexico",
        "zone": "Centro Historico",
        "zone_type": "turistica",
        "address": "5 de Mayo 49, Centro Historico, CDMX",
        "rationale": "Zona de alta densidad y variabilidad de demanda.",
    },
    {
        "address_id": "MXGDL-001",
        "city": "Guadalajara",
        "zone": "Providencia",
        "zone_type": "premium",
        "address": "Av. Americas 1254, Providencia, Guadalajara",
        "rationale": "Zona premium en segunda ciudad relevante.",
    },
    {
        "address_id": "MXGDL-002",
        "city": "Guadalajara",
        "zone": "Chapalita",
        "zone_type": "residencial",
        "address": "Av. Guadalupe 1450, Chapalita, Guadalajara",
        "rationale": "Zona residencial de ingreso medio-alto.",
    },
    {
        "address_id": "MXGDL-003",
        "city": "Guadalajara",
        "zone": "Centro",
        "zone_type": "alta demanda",
        "address": "Av. Juarez 211, Centro, Guadalajara",
        "rationale": "Zona central con alta densidad comercial.",
    },
    {
        "address_id": "MXMTY-001",
        "city": "Monterrey",
        "zone": "San Pedro",
        "zone_type": "premium",
        "address": "Calzada del Valle 400, San Pedro Garza Garcia",
        "rationale": "Zona premium con alta competencia.",
    },
    {
        "address_id": "MXMTY-002",
        "city": "Monterrey",
        "zone": "Tecnologico",
        "zone_type": "universitaria",
        "address": "Av. Eugenio Garza Sada 2501, Monterrey",
        "rationale": "Zona universitaria con demanda recurrente.",
    },
    {
        "address_id": "MXMTY-003",
        "city": "Monterrey",
        "zone": "Centro",
        "zone_type": "alta demanda",
        "address": "Padre Mier 201, Centro, Monterrey",
        "rationale": "Zona central para comparar tiempos y disponibilidad.",
    },
    {
        "address_id": "MXPUE-001",
        "city": "Puebla",
        "zone": "Angelopolis",
        "zone_type": "premium",
        "address": "Blvd. del Nino Poblano 2510, Puebla",
        "rationale": "Zona comercial premium.",
    },
    {
        "address_id": "MXPUE-002",
        "city": "Puebla",
        "zone": "Centro",
        "zone_type": "alta demanda",
        "address": "Av. Reforma 113, Centro, Puebla",
        "rationale": "Zona historica con mezcla de usuarios y oferta.",
    },
    {
        "address_id": "MXQRO-001",
        "city": "Queretaro",
        "zone": "Juriquilla",
        "zone_type": "residencial",
        "address": "Blvd. Universitario 1000, Juriquilla, Queretaro",
        "rationale": "Zona residencial de crecimiento.",
    },
    {
        "address_id": "MXQRO-002",
        "city": "Queretaro",
        "zone": "Centro Sur",
        "zone_type": "corporativa",
        "address": "Blvd. Bernardo Quintana 7001, Queretaro",
        "rationale": "Zona corporativa para comparar tiempos y fees.",
    },
]
